In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import statsmodels.api as sm

in_file = 'C:/vPhrase/Projects/Analytics_Features/Python/{}'
in_data = pd.read_excel(in_file.format('o_ring_failure.xlsx'))
in_data

In [2]:
# Data
in_data = pd.read_excel("datasets/o_ring_failure.xlsx", engine="openpyxl")
# target = np.array(ring_failure.loc[:, "number_experiencing_thermal_distress"])
# ring_failure.drop(columns=["number_experiencing_thermal_distress"], inplace=True)
# train_array = np.array(ring_failure)

In [3]:
Y = in_data['number_experiencing_thermal_distress']
X = in_data.drop(['number_experiencing_thermal_distress'], axis=1)

In [4]:
X = sm.add_constant(X)
X

/home/aumaron/Desktop/other_projects/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2580: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

    const  launch_temp_in_f  leak_check_pressure_psi  temporal_order_of_flight
0     1.0                66                       50                         1
1     1.0                70                       50                         2
2     1.0                69                       50                         3
3     1.0                68                       50                         4
4     1.0                67                       50                         5
5     1.0                72                       50                         6
6     1.0                73                      100                         7
7     1.0                70                      100                         8
8     1.0                57                      200                         9
9     1.0                63                      200                        10
10    1.0                70                      200                        11
11    1.0                78                      200                        12
12    1.0                67                      200                        13
13    1.0                53                      200                        14
14    1.0                67                      200                        15
15    1.0                75                      200                        16
16    1.0                70                      200                        17
17    1.0                81                      200                        18
18    1.0                76                      200                        19
19    1.0                79                      200                        20
20    1.0                75                      200                        21
21    1.0                76                      200                        22
22    1.0                58                      200                        23

In [5]:
#Linear regression with lasso penalty and only positive coefficients
lm_lasso_sk = linear_model.Lasso(alpha=1, fit_intercept=False, positive=True)
lm_lasso_sk.fit(X, Y)
print(lm_lasso_sk.coef_)

[0.        0.        0.0025622 0.       ]

In [6]:
# StatsModels
#Linear regression with lasso penalty
lm_lasso_sm = sm.OLS(Y, X)
results_lasso = lm_lasso_sm.fit_regularized(method='elastic_net', alpha=1, L1_wt=1.0)
print(results_lasso.params)

const                       0.000000
launch_temp_in_f            0.000000
leak_check_pressure_psi     0.002562
temporal_order_of_flight    0.000000
dtype: float64

In [7]:
np.all(lm_lasso_sk.coef_ == results_lasso.params)

True

In [8]:
np.arange(0.3, 2, 0.1).shape

(17,)

In [9]:
set_1 = ['SKlearn_'+str(i) for i in range(4)]
set_2 = ['SM_'+str(i) for i in range(4)]

In [23]:
out_frame_sk_pos = pd.DataFrame(data=np.zeros((17, 9))
                        , columns = [['alpha'] + set_1 + set_2])

out_frame_sk_pos

   alpha SKlearn_0 SKlearn_1 SKlearn_2 SKlearn_3 SM_0 SM_1 SM_2 SM_3
0    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
1    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
2    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
3    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
4    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
5    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
6    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
7    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
8    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
9    0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
10   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
11   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
12   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
13   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
14   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
15   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0
16   0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.0  0.0

In [26]:
# Check the results for multipe values of alpha
# sklearn model returns ONLY POSITIVE
counter = 0
for alpha_val in np.arange(0.3, 2, 0.1):
    lm_lasso_sk = linear_model.Lasso(alpha=alpha_val, fit_intercept=False, positive=True)
    lm_lasso_sk.fit(X, Y)

    lm_lasso_sm = sm.OLS(Y, X)
    results_lasso = lm_lasso_sm.fit_regularized(method='elastic_net', alpha=alpha_val, L1_wt=1.0)

    out_frame_sk_pos.iloc[counter, 0] = alpha_val
    out_frame_sk_pos.iloc[counter, 1:5] = lm_lasso_sk.coef_
    out_frame_sk_pos.iloc[counter, 5:9] = list(results_lasso.params)
    counter+=1

In [27]:
out_frame_sk_pos

   alpha SKlearn_0 SKlearn_1 SKlearn_2 SKlearn_3 SM_0      SM_1      SM_2 SM_3
0    0.3       0.0       0.0  0.002588       0.0  0.0  0.000000  0.002588  0.0
1    0.4       0.0       0.0  0.002584       0.0  0.0  0.000000  0.002584  0.0
2    0.5       0.0       0.0  0.002580       0.0  0.0  0.000000  0.002580  0.0
3    0.6       0.0       0.0  0.002577       0.0  0.0  0.000000  0.002577  0.0
4    0.7       0.0       0.0  0.002573       0.0  0.0  0.000000  0.002573  0.0
5    0.8       0.0       0.0  0.002569       0.0  0.0  0.000000  0.002569  0.0
6    0.9       0.0       0.0  0.002566       0.0  0.0  0.000000  0.002566  0.0
7    1.0       0.0       0.0  0.002562       0.0  0.0  0.000000  0.002562  0.0
8    1.1       0.0       0.0  0.002559       0.0  0.0  0.000000  0.002559  0.0
9    1.2       0.0       0.0  0.002555       0.0  0.0 -0.001151  0.002997  0.0
10   1.3       0.0       0.0  0.002551       0.0  0.0 -0.000981  0.002928  0.0
11   1.4       0.0       0.0  0.002548       0.0  0.0 -0.000811  0.002859  0.0
12   1.5       0.0       0.0  0.002544       0.0  0.0 -0.000641  0.002790  0.0
13   1.6       0.0       0.0  0.002540       0.0  0.0 -0.000471  0.002721  0.0
14   1.7       0.0       0.0  0.002537       0.0  0.0  0.000000  0.002537  0.0
15   1.8       0.0       0.0  0.002533       0.0  0.0  0.000000  0.002533  0.0
16   1.9       0.0       0.0  0.002530       0.0  0.0  0.000000  0.002530  0.0

In [28]:
out_frame_sk_both = pd.DataFrame(data=np.zeros((17, 9))
                        , columns = [['alpha'] + set_1 + set_2])

In [31]:
# Check the results for multipe values of alpha
# sklearn model returns positive and negative coefficients
counter = 0
for alpha_val in np.arange(0.3, 2, 0.1):
    lm_lasso_sk = linear_model.Lasso(alpha=alpha_val, fit_intercept=False, positive=False)
    lm_lasso_sk.fit(X, Y)

    lm_lasso_sm = sm.OLS(Y, X)
    results_lasso = lm_lasso_sm.fit_regularized(method='elastic_net', alpha=alpha_val, L1_wt=1.0)

    out_frame_sk_both.iloc[counter, 0] = alpha_val
    out_frame_sk_both.iloc[counter, 1:5] = lm_lasso_sk.coef_
    out_frame_sk_both.iloc[counter, 5:] = list(results_lasso.params)
    counter+=1

In [32]:
out_frame_sk_both

   alpha SKlearn_0 SKlearn_1 SKlearn_2 SKlearn_3 SM_0      SM_1      SM_2 SM_3
0    0.3       0.0  -0.00268  0.003617      -0.0  0.0  0.000000  0.002588  0.0
1    0.4       0.0  -0.00251  0.003548      -0.0  0.0  0.000000  0.002584  0.0
2    0.5       0.0  -0.00234  0.003479      -0.0  0.0  0.000000  0.002580  0.0
3    0.6       0.0  -0.00217  0.003410      -0.0  0.0  0.000000  0.002577  0.0
4    0.7       0.0  -0.00200  0.003341      -0.0  0.0  0.000000  0.002573  0.0
5    0.8       0.0  -0.00183  0.003272      -0.0  0.0  0.000000  0.002569  0.0
6    0.9       0.0  -0.00166  0.003204      -0.0  0.0  0.000000  0.002566  0.0
7    1.0       0.0  -0.00149  0.003135      -0.0  0.0  0.000000  0.002562  0.0
8    1.1       0.0  -0.00132  0.003066      -0.0  0.0  0.000000  0.002559  0.0
9    1.2       0.0  -0.00115  0.002997      -0.0  0.0 -0.001151  0.002997  0.0
10   1.3       0.0  -0.00098  0.002928      -0.0  0.0 -0.000981  0.002928  0.0
11   1.4       0.0  -0.00081  0.002859      -0.0  0.0 -0.000811  0.002859  0.0
12   1.5       0.0  -0.00064  0.002790      -0.0  0.0 -0.000641  0.002790  0.0
13   1.6       0.0  -0.00047  0.002721      -0.0  0.0 -0.000471  0.002721  0.0
14   1.7       0.0  -0.00030  0.002652      -0.0  0.0  0.000000  0.002537  0.0
15   1.8       0.0  -0.00013  0.002583      -0.0  0.0  0.000000  0.002533  0.0
16   1.9       0.0  -0.00000  0.002530      -0.0  0.0  0.000000  0.002530  0.0